---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vets
  template:
    metadata:
      labels:
        app: vets
    spec:
      containers:
      - image: theshipyard/vets-app:0.0.2
        name: vets
        ports:
        - containerPort: 8000
