---
apiVersion: v1
data:
  password: {{ database.password }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-pass
  namespace: {{ environment }}-{{ .Release.Name }}
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      containers:
      - image: {{ database.image }}:{{ database.version }}
        name: {{ .Release.Name }}-db
        ports:
        - containerPort: {{ database.port }}
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-db-pass
                key: password
          - name: POSTGRES_PORT
            value: {{ database.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  ports:
  - port: {{ database.port }}
    targetPort: {{ database.port }}
  selector:
    app: {{ .Release.Name }}-db
