---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $.Release.Name }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: {{ .Values.project_description }}
  sourceRepos:
  - 'git@github.com:w3s7y/fluffy-octo-telegram.git'
  - 'https://prometheus-community.github.io/helm-charts'
  - 'https://artifacthub.github.io/helm-charts'
  - 'https://argoproj.github.io/argo-helm'
  - 'https://charts.bitnami.com/bitnami'
  - 'https://helm.elastic.co'
  - 'https://helm.releases.hashicorp.com'
  - 'https://jp-gouin.github.io/helm-openldap'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding
    - group: 'apiextensions.k8s.io'
      kind: CustomResourceDefinition
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'admissionregistration.k8s.io'
      kind: MutatingWebhookConfiguration
    - group: 'admissionregistration.k8s.io'
      kind: ValidatingWebhookConfiguration

{{- range .Values.argo_apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $.Release.Name }}
  syncPolicy:
    automated: {}
    syncOptions:
    {{- range .sync_options }}
    - {{ . | quote }}
    {{- end }}
  source:
    repoURL: {{ .repo }}
    chart: {{ .chart }}
    targetRevision: {{ .version }}
    {{- if .helm_values }}
    helm:
      values: |
      {{- toYaml .helm_values | nindent 8 }}
    {{- end }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .namespace }}
{{- end }}
