---
environment: dev
vets:
  replicas: 1
  image:
    name: theshipyard/vets-app
    version: 0.0.9
  port: 8000
  debug: True
database:
  image:
    name: postgres
    version: 15.2
  host: vets-database
  port: 5432
  name: dev-vets
  user: vets-app
