---
root_domain: vets.internal
environment: default
vets:
  replicas: 1
  image:
    name: theshipyard/vets-app
    version: 0.0.0
  port: 8000
  debug: False
database:
  pgadmin:
    enabled: false
    sidecar:
      image: dpage/pgadmin4
      tag: 6.21
    ingress:
      uri: pgadmin
  claim: "1Gi"
  image:
    name: postgres
    version: 15.2
  host: vets-database
  port: 5432
  name: dev-vets
  user: vets-app
