---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: vets-workflow
spec:
  entrypoint: vets-ci-workflow
  templates:
  - name: vets-ci-workflow
    steps:
    - - name: pycodestyle
        template: pycodestyle
    - - name: django-tests
        template: djangotests
    - - name: build-vets
        template: build-vets
    - - name: tag-vets
        template: tag-vets
    - - name: push-vets
        template: push-vets
    - - name: update-deploy-descriptor-dev
        template: update-dd

  - name: pycodestyle
    container:
      image: python:alpine3.16
      command: [sh, -c]
      args:
        - "pip install application/requirements.txt"
        - "pycodestyle application"
  - name: djangotests
    container:
      image: python:alpine3.16
      command: [sh, -c]
      args:
        - "pip install application/requirements.txt"
        - "python application/manage.py test"
  - name: build-vets
    container:
      image: python:alpine3.16
      command: [sh, -c]
      args:
        - "echo build"
  - name: tag-vets
    container:
      image: python:alpine3.16
      command: [sh, -c]
      args:
        - "echo tag"
  - name: push-vets
    container:
      image: python:alpine3.16
      command: [sh, -c]
      args:
        - "echo push"
  - name: updatedd
    container:
      image: alpine/git:2.36.3
      command: [sh, -c]
      args:
        - "echo $(git --version)"
