---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: buildkit
  annotations:
    workflows.argoproj.io/description: |
      Build and push an image using Docker Buildkit.
      This does not need privileged access, unlike Docker in Docker (DIND).
    workflows.argoproj.io/maintainer: '@w3s7y'
    workflows.argoproj.io/tags: buildkit
    workflows.argoproj.io/version: '>= 2.9.0'
spec:
  templates:
    - name: build
      inputs:
        parameters:
          # Name of the image (including org e.g. 'theshipyard/vets-app')
          - name: image
          # push to the remote after build?
          - name: push
          # wokringdir (where the Dockerfile is)
          - name: workdir
            value: src
      volumes:
        - name: docker-config
          secret:
            secretName: docker-config
      container:
        image: moby/buildkit:v0.11.4-rootless
        volumeMounts:
          - name: workdir
            mountPath: /workdir
          - name: docker-config
            mountPath: /.docker
        workingDir: "/workdir/{{ inputs.parameters.workdir }}"
        env:
          - name: BUILDKITD_FLAGS
            value: --oci-worker-no-process-sandbox
          - name: DOCKER_CONFIG
            value: /.docker
        command:
          - buildctl-daemonless.sh
        args:
        - >
          build --metadata-file /workdir/buildkit-metadata.json
          --frontend dockerfile.v0 --local context=.
          --local dockerfile=. --output
          type=image,name=docker.io/{{ inputs.parameters.image }},
          push={{ inputs.parameters.push }},push-by-digest=true
