apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vets-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: vets
    namespace: "{{ .Values.environment }}-vets"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vets

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  DJANGO_SETTINGS_MODULE: "djangorestapi.settings"
  DJANGO_DATABASE: "main"
  DJANGO_CACHE: "redis"
  DJANGO_DEBUG: "{{ .Values.vets.debug }}"
  POSTGRES_USER: "{{ .Values.database.user }}"
  POSTGRES_HOST: "{{ .Values.database.host }}"
  POSTGRES_NAME: "{{ .Values.database.name }}"
  POSTGRES_PORT: "{{ .Values.database.port }}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-database
data:
  POSTGRES_USER: "{{ .Values.database.user }}"
  POSTGRES_DB: "{{ .Values.database.name }}"
  PGDATA: "/var/lib/postgresql/data/vets-data"
