---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  DJANGO_SETTINGS_MODULE: "djangorestapi.settings-k8s"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-database
data:
  POSTGRES_USER: "vets-app"
  POSTGRES_PASSWORD: "vets-pass"
  POSTGRES_DB: "vets"
  PGDATA: "/var/lib/postgresql/data/vets-data"