---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-database
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-database
  serviceName: "{{ .Release.Name }}-database"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:15.2
        ports:
        - containerPort: 5432
          name: db
        - containerPort: 8080
          name: adminer
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        envFrom:
          - configMapRef:
              name: "{{ .Release.Name }}-database"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 10Gi
