---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-database
data:
  POSTGRES_USER: "vets-app"
  POSTGRES_PASSWORD: "vets-pass"
  POSTGRES_DB: "vets"
  PGDATA: "/var/lib/postgresql/data/vets-data"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-database
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-database
  serviceName: "{{ .Release.Name }}-database"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:15.2
        ports:
        - containerPort: 5432
          name: db
        - containerPort: 8080
          name: adminer
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        envFrom:
          - configMapRef:
              name: "{{ .Release.Name }}-database"
              optional: false
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database
  labels:
    app: {{ .Release.Name }}-database
spec:
  ports:
  - port: 5432
    name: db
  - port: 8080
    name: adminer
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-database
