---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: vets-database
  labels:
    app: vets-database
spec:
  ports:
  - port: 5432
    name: db
  selector:
    app: {{ .Release.Name }}-database

{{- if .Values.database.pgadmin.enabled | default false }}
---
apiVersion: v1
kind: Service
metadata:
  name: vets-pgadmin
  labels:
    app: vets-pgadmin
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: {{ $.Release.Name }}-database
{{- end }}