# Generated by Django 4.2.7 on 2023-11-09 01:07

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('address_line_3', models.CharField(blank=True, max_length=200)),
                ('address_line_4', models.CharField(blank=True, max_length=200)),
                ('org_area', models.CharField(choices=[('Shropshire', 'Shropshire and North Wales'), ('Cheshire', 'Cheshire and Wirral'), ('Greater Manchester', 'Greater Manchester')], max_length=100)),
                ('post_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('middle_names', models.CharField(blank=True, max_length=200, null=True)),
                ('primary_contact_telephone', models.CharField(max_length=100)),
                ('secondary_contact_telephone', models.CharField(blank=True, max_length=100)),
                ('home_address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vets.address')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('human_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vets.human')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('vets.human',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vets.address')),
            ],
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('human_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='vets.human')),
                ('salary', models.IntegerField()),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('base_surgery', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vets.surgery')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('vets.human',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('Canine', 'Canine'), ('Feline', 'Feline'), ('Equidae', 'Equidae')], max_length=200)),
                ('dob', models.DateTimeField()),
                ('dod', models.DateTimeField(blank=True, null=True)),
                ('chip_id', models.BigIntegerField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vets.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='registered_surgery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vets.surgery'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date_time', models.DateTimeField()),
                ('details', models.TextField(default='Nature of Appointment: ')),
                ('outcome', models.TextField(default='Outcomes / Future Treatments: ')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vets.pet')),
                ('surgery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vets.surgery')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vets.client')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vets.vet')),
            ],
        ),
    ]
