name: Vets CI / CD Workflow

on:
  push:
    branches: [ "feature/*", "fix/*", "dev", "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # Run from UI

# Set the vars to let django to run local db/caches
env:
  DJANGO_CACHE: local
  DJANGO_DATABASE: local

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r application/requirements.txt
    - name: Make Migrations
      run: |
        python application/manage.py makemigrations
        python application/manage.py migrate
    - name: Run Tests
      run: |
        python application/manage.py test
