name: Vets CI / CD Workflow

on:
  push:
    branches: [ "feature/*", "fix/*", "dev", "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  # Run from UI

env:
  # Set the vars to let django know to run up local db/caches for testing
  DJANGO_CACHE: "local"
  DJANGO_DATABASE: "local"
  DJANGO_DEBUG: "True"
  DJANGO_SECRET_KEY: "This_horse_is_battery_only_for_staple_0123456789"

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        terraform-version: [1.3, 1.4]
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform-version }}
      - run: terraform -version
      - run: terraform fmt -check -recursive

  python-tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r application/requirements.txt
    - name: Make Migrations
      run: |
        python application/manage.py makemigrations
        python application/manage.py migrate
    - name: Run Tests
      run: |
        python application/manage.py test
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vets-app:latest